# Generated by Django 2.2.3 on 2019-08-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20190731_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekplan',
            name='days',
        ),
        migrations.AddField(
            model_name='dayplan',
            name='weekPlan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plans.WeekPlan'),
        ),
    ]
