# Generated by Django 2.2.3 on 2019-08-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20190802_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='weekPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.WeekPlan'),
        ),
    ]
