# Generated by Django 2.2.3 on 2019-08-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20190802_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayplan',
            name='weekPlan',
        ),
        migrations.AddField(
            model_name='weekplan',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='plans.DayPlan'),
        ),
    ]
