# Generated by Django 2.2.3 on 2019-08-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20190802_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekplan',
            name='days',
            field=models.ManyToManyField(blank=True, to='plans.DayPlan'),
        ),
    ]
