# Generated by Django 2.2.3 on 2019-08-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='commonItems',
            new_name='common_items',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='requiresFruit',
            new_name='requires_fruit',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='typeMeal',
            new_name='type_meal',
        ),
    ]
