# Generated by Django 2.2.3 on 2019-07-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='meals',
            field=models.ManyToManyField(to='meals.Meal'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='quantity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='meal',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='meal',
            name='requiresFruit',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='servings',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='meal',
            name='typeMeal',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('GENERIC', 'Generic')], default='GENERIC', max_length=100),
        ),
    ]
