# Generated by Django 2.2.3 on 2019-07-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20190725_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
