# Generated by Django 2.2.3 on 2019-07-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_commonitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonitem',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='meal',
            name='commonItems',
            field=models.ManyToManyField(to='meals.CommonItem'),
        ),
    ]
