# Generated by Django 2.2.3 on 2019-07-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_auto_20190725_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='servings',
        ),
    ]
