# Generated by Django 2.2.3 on 2019-07-28 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_remove_meal_servings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='commonItems',
        ),
        migrations.AddField(
            model_name='meal',
            name='commonItems',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='meals.CommonItem'),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='meals.Ingredient'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='requiresFruit',
            field=models.BooleanField(default=False),
        ),
    ]
