# Generated by Django 2.2.3 on 2019-07-28 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_auto_20190728_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='commonItems',
        ),
        migrations.AddField(
            model_name='meal',
            name='commonItems',
            field=models.ManyToManyField(to='meals.CommonItem'),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='', max_length=200)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(through='meals.Membership', to='meals.Ingredient'),
        ),
    ]
